// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hifweegpakeoznvbqfwn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpZndlZWdwYWtlb3pudmJxZnduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0ODQ2OTksImV4cCI6MjA2MDA2MDY5OX0.U92muAPwpaxfyLSIDEmKi8M6ubC4z1LQEEkb5ek6Y5Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);